# The Docker image that will be used to build your app
image: python:3.8

stages:
  - build
  - deploy

before_script:
  - apt-get update && apt-get install -y git
  - pip install -r requirements.txt
  - pip install Sphinx sphinx-rtd-theme

build_docs:
  stage: deploy
  script:
    - sphinx-build -b html ./ public/
    - echo "Documentation deployed" > public/deploy.txt
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  script:
    - mv public_tmp public
    - echo "Documentation deployed" > public/deploy.txt
  artifacts:
    paths:
      - public
  only:
    - master